/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package portalnoticias;

import Modelos.ConexionDB;
import java.awt.Color;
import java.awt.Font;       
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author jovie
 */
public class login extends javax.swing.JFrame {

    int xMouse, yMouse;
    private int intentos = 0;
    ConexionDB cc = new ConexionDB();
    Connection con = cc.getConneccion();
    //Connection con = cc.Connection();
    
    public login() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        BLogin.requestFocus();
    }
    
     public void validar() {
        int resultado = 0;
        String pass = String.valueOf(Password.getPassword());
        String usuario = Usuario.getText();
        String sql = "select * from usuarios where ID_USUARIO='" + usuario + "' and PASSWORD='" + pass + "'";

        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                resultado = 1;
                if (resultado == 1) {
                    new Principal().setVisible(true);
                    //this.setVisible(false);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Usuario no autorizado!", "Usuario no existe", JOptionPane.ERROR_MESSAGE);
                intentos = intentos + 1;
                if (intentos == 3) {
                    JOptionPane.showMessageDialog(null, "Ha excedido el limite de 3 intentos", "Intentos", JOptionPane.ERROR_MESSAGE);
                    System.exit(0);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en consultar la base de datos " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        IconoCirculo = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        TitleLogin = new javax.swing.JLabel();
        BLogin = new javax.swing.JButton();
        TitleUsuario = new javax.swing.JLabel();
        TitleContra = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        Usuario = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel.setBackground(new java.awt.Color(37, 37, 37));
        Panel.setForeground(new java.awt.Color(255, 255, 255));
        Panel.setToolTipText("");
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconoCirculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Circulos.png"))); // NOI18N
        Panel.add(IconoCirculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        header.setBackground(new java.awt.Color(37, 37, 37));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(37, 37, 37));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 0, 40, 40));

        Panel.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 90));

        jPanel2.setBackground(new java.awt.Color(37, 37, 37));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleLogin.setFont(new java.awt.Font("Corbel Light", 0, 92)); // NOI18N
        TitleLogin.setForeground(new java.awt.Color(255, 255, 255));
        TitleLogin.setText("LOGIN");
        jPanel2.add(TitleLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 110));

        BLogin.setBackground(new java.awt.Color(255, 221, 0));
        BLogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BLogin.setForeground(new java.awt.Color(0, 0, 0));
        BLogin.setText("LOGIN");
        BLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BLogin.setFocusPainted(false);
        BLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BLoginMouseExited(evt);
            }
        });
        BLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLoginActionPerformed(evt);
            }
        });
        jPanel2.add(BLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 460, 50));

        TitleUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TitleUsuario.setForeground(new java.awt.Color(255, 255, 255));
        TitleUsuario.setText("Usuario");
        jPanel2.add(TitleUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 170, -1));

        TitleContra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TitleContra.setForeground(new java.awt.Color(255, 255, 255));
        TitleContra.setText("Contraseña");
        jPanel2.add(TitleContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 170, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 213, 460, 10));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 460, 10));

        Usuario.setBackground(new java.awt.Color(37, 37, 37));
        Usuario.setForeground(new java.awt.Color(153, 153, 153));
        Usuario.setText("Ingrese su Usuario");
        Usuario.setBorder(null);
        Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UsuarioMousePressed(evt);
            }
        });
        jPanel2.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 460, 30));

        Password.setBackground(new java.awt.Color(37, 37, 37));
        Password.setForeground(new java.awt.Color(153, 153, 153));
        Password.setText("**********");
        Password.setBorder(null);
        Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PasswordMousePressed(evt);
            }
        });
        jPanel2.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 460, 30));

        Panel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 460, 490));

        getContentPane().add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLoginActionPerformed
        validar();
    }//GEN-LAST:event_BLoginActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        Font f = jLabel1.getFont();
        jLabel1.setForeground(Color.RED);
        jLabel1.setFont(f.deriveFont(f.getStyle() | Font.BOLD));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        Font f = jLabel1.getFont();
        jLabel1.setFont(f.deriveFont(f.getStyle() & ~Font.BOLD));
        jLabel1.setForeground(Color.white);
    }//GEN-LAST:event_jLabel1MouseExited

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
        
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void BLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BLoginMouseEntered
        BLogin.setBackground(new Color(255,242,159));
    }//GEN-LAST:event_BLoginMouseEntered

    private void BLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BLoginMouseExited
        BLogin.setBackground(new Color(255,221,0));
    }//GEN-LAST:event_BLoginMouseExited

    private void UsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuarioMousePressed
        if (Usuario.getText().equals("Ingrese su Usuario")){
            Usuario.setText("");
            Usuario.setForeground(Color.white);
        } 
        if (String.valueOf(Password.getPassword()).isEmpty()){
            Password.setText("**********");
            Password.setForeground(new Color(153,153,153));  
        }
    }//GEN-LAST:event_UsuarioMousePressed

    private void PasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordMousePressed
        if (String.valueOf(Password.getPassword()).equals("**********")){
            Password.setText("");
            Password.setForeground(Color.white);
        }
        if (Usuario.getText().isEmpty()){
            Usuario.setText("Ingrese su Usuario");
            Usuario.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_PasswordMousePressed

    private void BLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BLoginMouseClicked
        // REDIRIGE A LA PAGINA PRINCIPAL:
    }//GEN-LAST:event_BLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BLogin;
    private javax.swing.JLabel IconoCirculo;
    private javax.swing.JPanel Panel;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel TitleContra;
    private javax.swing.JLabel TitleLogin;
    private javax.swing.JLabel TitleUsuario;
    private javax.swing.JTextField Usuario;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
